# Site Info
title: Test Blog
tagline: ''
description: 'Developer'
baseurl: ""
url: http://127.0.0.1:4000 #https://wyjung.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: test
  description: Developer
  #gravatar:  # md5 hash of your email address
  contact:
    #linkedin:
    github:    https://github.com/wyjung
    # facebook:  <hide>
    # twitter:
    # weibo:
    email: wyjung84@gamil.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Today I Learned : '/blog/categories/#til' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: true # whether support mathjax
google_analytics_token:
disqus_short_name:

